#!/bin/bash

#任务名
TASKNAME=
#任务日期
TASKDATA=


#生成当前日期
gen_date()
{
	TASKDATA=`date +%Y%m%d`
	return $?
}

#输入task名
gen_name()
{	
	read -p "Your Task name(${1}):  " TASKNAME
	return $?
}

# 创建任务
create_task()
{
	gen_date
	gen_name $1

	local temp="${1}/${TASKDATA}-${TASKNAME}"

	if [ "$1" = "hotfix" ]; then
		git pull origin master:master>/dev/null 2>&1
		wait
		git checkout master>/dev/null 2>&1
	elif [ "$1" = "feature" ]; then
		git pull origin develop:develop>/dev/null 2>&1
		wait
		git checkout develop>/dev/null 2>&1
	else
		usage
	fi

	wait
	git checkout -b ${temp}>/dev/null 2>&1


	if [ $? -eq 0 ]; then
		echo -e "🍻 Success created task: \033[32m${temp}\033[0m"
	else
		echo -e "💊 failure!"
	fi

	return $?
}


#添加文件
add_task()
{
	local filelist
	if [ -z "$1" ]; then

		filelist=`git status --porcelain --u | sed 's/^...//g'`

		[ -z "$filelist" ] && printf "未发现修改的文件！\n" && exit 1
	else
		filelist=$1	
	fi

	echo -e "\033[33m==>\033[1m \033[37m Check Php Syntax... \033[0m"

	local pass=0
	for file in $filelist; do
		if [ -f "$file" ] && [ "${file##*.}s" = "phps" ]; then

			local errortips;

			`php -l $file >/dev/null 2>/tmp/php_error.log`

			[ "$?" -gt 0 ] \
			&& pass=1 \
			&& errortips=$(cat /tmp/php_error.log) \
			&& echo -e "\033[32m${file}\033[0m\033[31m ✘\033[0m" \
			&& echo -e "\033[41;37m${errortips}\033[0m" \
			|| echo -e "\033[32m${file}\033[0m\033[32m ✔\033[0m"
		fi
	done

	[ $pass -eq 1 ] && echo -e "\033[33m==>\033[1m \033[37m Please Fix ! \033[0m" && exit 1

	git add $filelist

	echo -e "\033[33m==>\033[1m \033[37m Success...🤙🤙🤙  \033[0m"

  return $?
}

#使用说明
usage()
{
	cat <<EOF
usage:   gtask [options]
options:
-s          "git status"
-c [h|f]
	    h "创建一个 hotfix 分支 base master"
	    f "创建一个 feature 分支 base develop"
-d    "删除本地非[master\develop\dev]分支  注意：当使用此选项时、其他选项不生效"
-a|--add    "--add=<file>. 添加到暂存区,并且检测php语法错误！默认为全部改动，但可以添加一个指定文件、注意： 当使用此选项时、其他选项不生效"
-m|--msg    "--msg=<msg>提交代码到仓库 必跟参数 message"

EOF

	exit 0
}

#判断参数
[ "$#" -eq 0 ] && usage

args=`getopt -o m::a::c:sdh --long add::,msg::,status -n "$0" -- "$@"`

eval set -- "$args"

while true; do
	case $1 in
		-s | --status)
			git status
			exit 0
			;;
	  	-m | --msg)
		    [ -z $2 ] && msg=fixbug || msg=$2
		    eval git commit -m $2
		    exit
	    	;;
	  	-h )
		    usage
		    shift
		    ;;
		-c )
			case $2 in
				f )
					create_task feature
					;;
				h )
					create_task hotfix
					;;
				fh | hf )
					create_task feature
					create_task hotfix
					;;
				* )
					usage

			esac
			exit 0
			;;
		-a | --add)
			add_task $2
			exit $?
			;;
		-d)
			read -p "Are You Sure?[y/n]" -s tag
			if [ $tag = "y" ]; then
				git checkout master && git branch | egrep -v "master|dev|test" | awk '{cmd="git branch -D "$1; system(cmd)}'
			fi
			exit 1;;
	  --)
	    shift
	    exit
	    ;;
	\?)
	    usage
		  exit
			;;
	esac
done
