#!/bin/bash

#任务名
TASKNAME=
#任务日期
TASKDATA=

#git 执行文件
GITPATH="/usr/bin/git"
#php解释器
PHPBIN="/usr/bin/env php -l"
# phpcs 检查到的错误信息
PHPCSLOGFILE=/tmp/check_result.txt
#php 语法错误日志文件
PHPERRORFILE=/tmp/php_error.log
#phpcs 执行
PHPCS="phpcs --standard=OSR0 --colors --encoding=utf-8 -n -p"
#gun-opt
GUNOPT="/usr/bin/env getopt"

FORMATSTUDIO="\033[37m|----------------------------------------------------------------------|\033[0m"

# 一个保存本地分支的数组
LOCALBRANCHS=

#选中的分支
SELECTBRANCH=

# 不带参数时出现选项，
# 带参数时，指定把某个索引分支 merge 到 指定索引分支
run_merge_branc()
{
	if [[ $1 = "abort" ]]; then
	    eval $GITPATH merge --abort
	    return $?
	fi

	select_branch $1

	eval exec $GITPATH merge $SELECTBRANCH
}




#列表出当前git下本地所有分支、并带上索引位置
#gt -b
ls_git_local_branch()
{

	select_branch $1

	eval exec $GITPATH checkout $SELECTBRANCH
}

show_local_branch()
{
	build_array_branch

	#当前分支
	local currentBranch=`eval $GITPATH branch | grep "^*" | cut -d " " -f 2`

	for (( i = 1; i < ${#LOCALBRANCHS[@]}; i++ )); do
		local selectBranchName=${LOCALBRANCHS[i]}
		local branchDesc=`eval $GITPATH config branch.$selectBranchName.description`
		
		[[ $selectBranchName = $currentBranch ]] \
		&& branchSelc="\033[32;40;5m [$i] - ${selectBranchName}\033[0m" \
		|| branchSelc="\033[32m [$i] - ${selectBranchName}\033[0m"
		
		[[ -n $branchDesc ]] && branchSelc="${branchSelc}   #desc:${branchDesc}"

		echo -e $branchSelc
	done
	
	return $?
}


# 选择分支
select_branch()
{	
	if [[ -z $1 ]]; then

		show_local_branch
		
		while [[ -z $SELECTBRANCH ]]; do
			read -ep "Select Your Branch Index: " index
			SELECTBRANCH=${LOCALBRANCHS[index]}
		done

	else
		
		if [[ $1 =~ ^[0-9]+$ ]]; then

			SELECTBRANCH=${LOCALBRANCHS[$1]}

			if [[ -z $SELECTBRANCH ]]; then
				echo "Please Select Branch Index"
				exit 1
			fi
		else
			SELECTBRANCH=$1
		fi

	fi

	return $?
}




# git branch 分支放到数组里
build_array_branch()
{
	local i=1

	for b in `eval $GITPATH branch | grep "" | sed -e 's/*/ /' -e 's/ //'`; do LOCALBRANCHS[$i]=$b; let i++; done;

	return $?
}


#生成当前日期
gen_date()
{
	TASKDATA=`date +%Y%m%d`
	return $?
}

#输入task名
gen_name()
{	
	read -p "Your Task name(${1}):  " TASKNAME
	return $?
}

# 创建任务
create_task()
{
	gen_date
	gen_name $1

	local temp="${1}/${TASKDATA}-${TASKNAME}"

	if [[ "$1" = "hotfix" ]]; then
		eval $GITPATH pull origin master:master
		eval $GITPATH checkout master
	elif [[ "$1" = "feature" ]]; then
		eval $GITPATH pull origin develop:develop
		eval $GITPATH checkout develop
	else
		usage
	fi

	eval $GITPATH checkout -b ${temp}

	if [[ $? -eq 0 ]]; then
		echo -e "🍻 Success created task: \033[32m${temp}\033[0m"
	else
		echo -e "💊 failure!"
	fi
	
	return $?
}


#添加文件
add_task()
{
	local filelist
	if [[ -z "$1" || $1 = "." ]]; then

		filelist=`eval $GITPATH status --porcelain --u | sed 's/^...//g'`

		[[ -z "$filelist" ]] && printf "未发现修改的文件！\n" && exit 1
	else
		filelist=$1	
	fi

	echo -e $FORMATSTUDIO
	echo -e "\033[37m|                         PHP语法检测开始                              |\033[0m\n"

	local pass=0
	local errortips

	for file in $filelist; do
		if [[ -f "$file" && "${file##*.}s" = "phps" ]]; then
			eval $PHPBIN $file >/dev/null 2>$PHPERRORFILE

			[[ "$?" -gt 0 ]] \
			&& pass=1 \
			&& errortips=$(cat $PHPERRORFILE) \
			&& echo -e "\t\033[32m${file}\033[0m\033[31m ✘\033[0m" \
			&& echo -e "\t\033[41;37m${errortips}\033[0m" \
			|| echo -e "\t\033[32m${file}\033[0m\033[32m ✔\033[0m"

			phpcsLog=`eval $PHPCS $file`

			if [[ ${phpcsLog:0:1} != "." ]]; then
				echo "$phpcsLog" >> $PHPCSLOGFILE
			fi

		fi
	done
	# test 
	if [[ $pass -eq 1 ]]; then
		#
		echo "" > $PHPCSLOGFILE
		echo -e "\n\033[37m|              当前提交PHP文件有语法错误、提交失败                     |\033[0m"
		echo -e "\033[37m|----------------------------------------------------------------------|\033[0m"
		exit 1
	fi
	echo -e "\n\033[37m|                         PHP语法检测通过                              |\033[0m"
	# test psr
	echo -e "\033[37m|----------------------------------------------------------------------|\033[0m"
	echo -e "\033[37m|                         PHPCS检测开始                                |\033[0m"

	if [[ -s $PHPCSLOGFILE ]]; then
		cat $PHPCSLOGFILE && rm $PHPCSLOGFILE
		echo -e "\n\033[37m|                  请修复代码格式!git提交失败                            \033[0m"
		echo -e "\033[37m|----------------------------------------------------------------------\033[0m"
		exit 1
	fi
	echo -e "\n\033[37m|                   未检测到格式错误的PHP文件                          \033[0m"
	echo -e "\033[37m|----------------------------------------------------------------------|\033[0m"

	eval $GITPATH add $filelist

	echo -e "\033[33m[SUCCESS]\033[1m \033[37m \t\tgit提交成功...🤙🤙🤙  \033[0m"

  return $?
}


push_pull()
{
	case $1 in
		l)
	  		eval $GITPATH pull
	   		;;
		s)
			eval $GITPATH push
			;;
		sf)
			eval $GITPATH push -f
			;;
		*)
			echo -e "The Options -p Only Support l or s!"
			;;
	esac
}

#删除分支
del_branch() {
	if [[ $1 = "all" ]]; then
		read -p "Are You Sure?[y/n]" -s tag
		if [[ $tag = "y" ]]; then
			exec eval $GITPATH checkout master && $GITPATH branch | egrep -v "master|dev|test" | awk '{cmd="git branch -D "$1; system(cmd)}'
		fi
	fi

	select_branch

	eval exec $GITPATH br -D $SELECTBRANCH
}


#使用说明
usage()
{
	echo -e "
\033[1;37mUSAGE \033[0m  [<options...>]

\033[1;37mOPTIONS\033[0m:
-b 
    查看本地所有分支
-s
    执行 git status

-c [<mode>]
    h 创建一个 hotfix 分支 基于 master 所以本地要有 master 分支
    f 创建一个 feature 分支 基于 develop 所以本地要有 develop 分支

-d [<index>]
    index=all 时删除本地非[master\develop\dev]分支  注意：当使用此选项时、其他选项不生效

-a|--add
    --add=<file>. 添加到暂存区,并且检测php语法错误！默认为全部改动，但可以添加一个指定文件、注意： 当使用此选项时、其他选项不生效
    gtask -a .
    gtask -a file

-m|--msg [<message>]
    默认 message=fixbug 提交代码到仓库 必跟参数 message
    gtask -mbug提交

--co [<index>]
    会出现本地可以切换的分支、index 可以某一个分支的索引位置，直接切到该选中分支 
    gtask --co 会列表所有可切换分支
    gtask --co 1 会切换到 1对应的分支

--merge [<index>]
	同 --co 一样的用法，把指定分支合并到当前所在分支 支持 abort

-p [l|s|sf]
    l git pull
    s git push
    sf git push --force
"
	exit 0
}

#判断参数
[[ "$#" -eq 0 ]] && usage

args=`eval $GUNOPT -o p:m:a:c:dbsh -l merge,co,add:,msg:,status -- $*`


eval set -- "${args}"


while true; do
	case $1 in
		-b)
			show_local_branch
			exit 0
			;;
		-p)
			shift
			push_pull $1
			exit 0
			;;
		-s | --status)
			eval $GITPATH status
			exit 0
			;;
	  	-m | --msg)
		    [[ ! -n $2 ]] && msg=fixbug || msg=$2
		    eval $GITPATH commit -m $2
		    exit 0
	    	;;
	  	-h )
		    usage
		    shift
		    ;;
		-c )
			case $2 in
				f )
					create_task feature
					;;
				h )
					create_task hotfix
					;;
				hf|fh )
					create_task feature
					create_task hotfix
					;;
				* )
					usage
					exit 0

			esac
			exit 0
			;;
		-a | --add)
			add_task $2
			exit 0
			;;
		-d)
			shift
			del_branch $2
			exit 0
			;;
		--co)
			shift
			ls_git_local_branch $2
			exit 0
			;;
		--merge)
			shift
			run_merge_branc $2
			exit 0
			;;
	  --)
		usage
		exit $?
	    ;;
	\?)
	    usage
		exit $?
		;;
	esac
done
